package reporters

import (
	"fmt"
	"os"
	"strings"

	"github.com/helloodokai/acig/internal/verdict"
)

func WriteMarkdown(v *verdict.Verdict, path string) error {
	md := FormatMarkdown(v)
	if path == "" || path == "-" {
		fmt.Println(md)
		return nil
	}
	return os.WriteFile(path, []byte(md), 0o644)
}

func FormatMarkdown(v *verdict.Verdict) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Acig Verdict: %s\n\n", strings.ToUpper(string(v.Decision))))
	sb.WriteString(fmt.Sprintf("**Risk:** %s | **Cost:** $%.4f | **Duration:** %dms\n\n", v.Risk, v.TotalCostUSD, v.TotalDurationMS))
	sb.WriteString(fmt.Sprintf("%s\n\n", v.Summary))

	if len(v.Findings) == 0 {
		sb.WriteString("No findings. Code looks clean.\n")
	} else {
		sb.WriteString("## Findings\n\n")
		for _, f := range v.Findings {
			severity := string(f.Severity)
			switch f.Severity {
			case verdict.SeverityBlocking:
				severity = "🚫 BLOCKING"
			case verdict.SeverityHigh:
				severity = "🔴 HIGH"
			case verdict.SeverityMedium:
				severity = "🟡 MEDIUM"
			case verdict.SeverityLow:
				severity = "🟢 LOW"
			case verdict.SeverityInfo:
				severity = "ℹ️ INFO"
			}
			sb.WriteString(fmt.Sprintf("### [%s] %s\n", severity, f.Title))
			sb.WriteString(fmt.Sprintf("- **Critic:** %s\n", f.Critic))
			if f.File != "" {
				loc := f.File
				if f.LineStart > 0 {
					loc += fmt.Sprintf(":%d", f.LineStart)
				}
				sb.WriteString(fmt.Sprintf("- **Location:** %s\n", loc))
			}
			sb.WriteString(fmt.Sprintf("\n%s\n\n", f.Detail))
			if f.SuggestedFix != "" {
				sb.WriteString(fmt.Sprintf("> **Suggested fix:** %s\n\n", f.SuggestedFix))
			}
		}
	}

	if len(v.CriticResults) > 0 {
		sb.WriteString("## Critic Results\n\n")
		sb.WriteString("| Critic | Model | Findings | Cost | Duration |\n")
		sb.WriteString("|--------|-------|----------|------|----------|\n")
		for _, cr := range v.CriticResults {
			errIndicator := ""
			if cr.Error != "" {
				errIndicator = " ⚠️"
			}
			sb.WriteString(fmt.Sprintf("| %s%s | %s | %d | $%.4f | %dms |\n",
				cr.Critic, errIndicator, cr.Model, len(cr.Findings), cr.CostUSD, cr.DurationMS))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("---\n*Generated by [acig](https://github.com/helloodokai/acig) • SHA: %s*\n", v.SHA))

	return sb.String()
}